---
title: "our planets with mass measurements"
author: "J. Dotson"
date: "8/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(ggplot2)
require(hexbin)
require(scales)
require(dplyr)
require(tidyverse)
require(readr)
require(RColorBrewer)
require(ggforce)
require(ggthemes)
require(gridExtra)
myecho=FALSE
knitr::opts_knit$set(root.dir = '../.')


```

Pull in my color palettes

```{r}
source("Rscripts/mycolors.R")
```



From planethistory_base:

```{r }
planets_m <- readRDS("RDS/planets_moreinfo.rds")
```

Focusing in on planets with measured mass and measured radii

```{r }
#dump calculated masses
planets_m <- planets_m %>% filter(fpl_bmassreflink != "<a refstr=CALCULATED_VALUE href=/docs/composite_calc.html target=_blank>Calculated Value</a>")

#dump calculated radii
planets_m <- planets_m %>% filter(fpl_radreflink != "<a refstr=CALCULATED_VALUE href=/docs/composite_calc.html target=_blank>Calculated Value</a>")
```

Ok, and let's set up a factor for kepler/k2 and other...

```{r}
planets_m$source <- rep("All Other Discoveries", nrow(planets_m))
jj <- which(planets_m$pl_instrument == "Kepler CCD Array")
planets_m$source[jj] <-"Kepler/K2 Discoveries"


planets_m$source <- factor(planets_m$source, levels=c("Kepler/K2 Discoveries","All Other Discoveries"))

count(planets_m, source)


```

```{r}
baseplot <- ggplot(planets_m) + theme_bw()

p1 <- baseplot + geom_point(aes(x=fpl_bmasse, y=fpl_rade,col=source),alpha=0.5) + scale_color_geert()
p1 <- p1 + scale_x_log10() + scale_y_log10()
print(p1)


p1 <- p1 + geom_errorbar(aes(x=fpl_bmasse,ymax=fpl_rade+fpl_radeerr1,ymin=fpl_rade+fpl_radeerr2,col=source),alpha=0.5)
p1 <- p1 + geom_errorbarh(aes(x=fpl_bmasse,y=fpl_rade,xmax=fpl_bmasse+fpl_bmasseerr1, xmin=fpl_bmasse+fpl_bmasseerr2,
                              col=source),alpha=0.5)
print(p1)

#neptune is 4Re and 17Me
p1 <- p1 + ylim(c(0.1,4)) + xlim(c(0.1, 20))
p1 <- p1 + xlab("Planet Mass in Earth Units") + ylab("Planet Radius in Earth Units")
p1 <- p1 + theme(legend.title = element_blank()) 
print(p1)

```

Out of curiosity, how many have measurements but no uncertainties?

```{r}
num_wo_Rerr <- sum(is.na(planets_m$fpl_radeerr1))
print(paste("Number without radius errors = ", num_wo_Rerr))

num_wo_Merr <- sum(is.na(planets_m$fpl_bmasseerr1))
print(paste("Number without mass errors = ", num_wo_Merr))

count(planets_m, fpl_bmassprov)
count(planets_m, pl_discmethod)
```



```{r}

earth_max <- 1.25
super_earth_max <- 2.0
neptune_max <- 6.0
jupiter_max <- 15.0

planets_m$size <- rep(NA, nrow(planets_m))

planets_m <- mutate(planets_m, size = ifelse(((fpl_rade > neptune_max) & (fpl_rade <= jupiter_max)), "Jupiter",
                                             ifelse(((fpl_rade > super_earth_max) & (fpl_rade <= neptune_max)), "Neptune",
                                                    ifelse(((fpl_rade > earth_max)& (fpl_rade <= super_earth_max)), "SuperEarth",
                                                           ifelse(((fpl_rade > 0) & (fpl_rade <= earth_max)), "Earth", "Huge")))))

count(planets_m, size)

planets_m$size <- factor(planets_m$size, levels=c("Earth","SuperEarth","Neptune","Jupiter","Huge"))


```


```{r}
baseplot <- ggplot(planets_m ) + theme_bw()

p2 <- baseplot + geom_bar(aes(x=size, fill=size)) + scale_fill_geert(palette="planets2")
print(p2)

p2 <- p2 + facet_wrap(~source)
p2 <- p2 + theme(axis.text.x = element_text(angle = 90, size=12,vjust=0.5)) + theme(legend.position = "none")
p2 <- p2 + theme(axis.text.y = element_text(size=12))
p2 <- p2 + theme(strip.text = element_text(size=16)) + theme(axis.title = element_text(size=14))
p2 <- p2 + ylab("Number")
p2 <- p2 + labs(title = "Exoplanets with Measured Mass and Radius")
p2 <- p2 + theme(plot.title = element_text(size=18, hjust=0.5))
print(p2)

```


How were the non Kepler ones discovered?

```{r}

notkep <- planets_m %>% filter(source == "All Other Discoveries")

count(notkep, pl_discmethod)

count(notkep, pl_facility)



```




