---
title: "Occurrence rate comparisons"
author: "J. Dotson"
date: "8/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(ggplot2)
require(hexbin)
require(scales)
require(dplyr)
require(tidyverse)
require(readr)
require(RColorBrewer)
require(ggforce)
require(ggthemes)
require(gridExtra)
myecho=FALSE
knitr::opts_knit$set(root.dir = '../.')

```

I did a very dangerous thing and compiled eta-earth -ish estimates from the literature.  Now lets plot them up...

```{r }
rates <- read_csv("inputs/eta_earth_summary.csv")
```

Sort 

```{r }
rates <- rates[order(rates$stellar_types,rates$HZ_definition, rates$size_range, rates$year,rates$reference),]
```

```{r}
baseplot <- ggplot(rates) + theme_bw()
p1 <- baseplot + geom_pointrange(aes(x=reference,y=eta, ymin=eta-Lsigma,ymax=eta+Usigma))
print(p1)

p1 <- p1 + coord_flip()
print(p1)

```


```{r}
rates$label <- paste(rates$reference,": ", rates$stellar_types, "; ", rates$HZ_definition, "; ", 
                     rates$size_range,"Re", sep="")
rates$label2 <- paste(rates$stellar_types, "; ", rates$HZ_definition, "; ", 
                     rates$size_range,"Re", sep="")
```


```{r}
baseplot <- ggplot(rates) + theme_bw()
p1 <- baseplot + geom_pointrange(aes(x=label,y=eta, ymin=eta-Lsigma,ymax=eta+Usigma))
p1 <- p1 + coord_flip()
print(p1)

baseplot <- ggplot(rates) + theme_bw()
p1 <- baseplot + geom_pointrange(aes(x=label2,y=eta, ymin=eta-Lsigma,ymax=eta+Usigma))
#p1 <- p1 + geom_text(aes(x=label2,y=1.4,label=reference),hjust="inward")
p1 <- p1 + coord_flip()
print(p1)

baseplot <- ggplot(rates) + theme_bw()
p1 <- baseplot + geom_pointrange(aes(x=label2,y=eta, ymin=eta-Lsigma,ymax=eta+Usigma))
p1 <- p1 + geom_text(aes(x=label2,y=1.4,label=reference),hjust="inward", size=3)
p1 <- p1 + ylab("Eta Earth") + xlab("")
p1 <- p1 + coord_flip()
print(p1)



```










